### ISSUE TITLE
Avatar command should sends avatar with better resolution

### ISSUE THREAD

**Issue by Xiaro** [kami-blue/bot#116]
Currently, the resolution of the avatar from the bot is too low, making it blur comparing to other bot (e.x. Dyno)
https://discordapp.com/channels/573954110454366214/634510679465918474/738801136487891136
https://discordapp.com/channels/573954110454366214/634510679465918474/738801243031601153
![image](https://user-images.githubusercontent.com/62033805/89058434-4900ce00-d32d-11ea-9fc0-75a91efd045c.png)

**Comment by dominikaaaa** [comment]
I mean, Dyno doesn't magically get a bigger resolution from discord's servers, it just displays it bigger

iirc the syntax was ?size=512

**Comment by Xiaro** [comment]
> I mean, Dyno doesn't magically get a bigger resolution from discord's servers, it just displays it bigger
> 
> iirc the syntax was ?size=512x512

Click on the image and open original, it is bigger

**Comment by dominikaaaa** [comment]
ah

dyno
```
https://cdn.discordapp.com/avatars/334854726233489409/53c7e3ef63deb3d5e0230e4310f071d7.png?size=256
```
ours
```
```
https://cdn.discordapp.com/avatars/334854726233489409/53c7e3ef63deb3d5e0230e4310f071d7.webp
```

turns out you can access the bigger resolution by changing the extension to png. why would discord even store both. bruh
