### ISSUE TITLE
;wiki command

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/bot#117]
searches an entry in wikipedia

**Comment by sourTaste000** [comment]
fuck wrong title

**Comment by humboldt123** [comment]
mfw. already did this in another bot and theres probably an npm module that already has this, ill take a look 🧐

**Comment by dominikaaaa** [comment]
what
bruhhhhhh you can do the same shit you did for lmgtfy

**Comment by dominikaaaa** [comment]
`https://en.wikipedia.org/w/index.php?search=[COMMAND ARGUMENTS]`

**Comment by dominikaaaa** [comment]
wikipedia automatically redirects that to the correct page

**Comment by humboldt123** [comment]
or you could be smart like that

**Comment by dominikaaaa** [comment]
> import whole npm module instead of just appending text

**Comment by zeroeightysix** [comment]
[js devs](https://www.npmjs.com/package/is-even)

**Comment by humboldt123** [comment]
mfw 🧐

**Comment by sourTaste000** [comment]
https://www.npmjs.com/package/wikijs
🤔
