### ISSUE TITLE
Starboard cringe 

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/bot#131]
basically starboard but for cringe ![](https://cdn.discordapp.com/attachments/573955213879410689/742065894817267742/Screenshot_20200809-130216.png)

**Comment by sourTaste000** [comment]
so make a starboard but for cringe

**Comment by sourTaste000** [comment]
if there is enough :shut:, forward the message to the channel?

**Comment by dominikaaaa** [comment]
yes 

2 is good I think
