### ISSUE TITLE
Sour taste

### ISSUE THREAD

**Issue by humboldt123** [kami-blue/bot#141]
Should be a contributor here

**Comment by dominikaaaa** [comment]
they are tho

**Comment by humboldt123** [comment]
I meant collaboratorer

**Comment by dominikaaaa** [comment]
I can make them collaborator once we move the more important commands such as ban to the Kotlin bot

**Comment by sourTaste000** [comment]
:trollface:

**Comment by sourTaste000** [comment]
so use kord or compile kotlin to js and still uses discord.js :joy:

**Comment by dominikaaaa** [comment]
compiling kotlin to JS is a stupid idea

**Comment by LittleDraily** [comment]
Make jda bot

**Comment by dominikaaaa** [comment]
kord > jda

**Comment by humboldt123** [comment]
mfw

**Comment by humboldt123** [comment]
Kord doesn't even have voice support
![image](https://user-images.githubusercontent.com/38266782/90303720-65008580-de7e-11ea-9eca-6f6bfee1cedf.png)

**Comment by sourTaste000** [comment]
That's why why have separate bots

0ps you can just type ':trollface:'

**Comment by dominikaaaa** [comment]
that's why we have 2 bots. and that's why your suggestion of compiling kotlin to JS is stupid

**Comment by humboldt123** [comment]
> 0ps you can just type ':trollface:'
Is who made this an emote?

**Comment by sourTaste000** [comment]
> that's why we have 2 bots. and that's why your suggestion of compiling kotlin to JS is stupid 

 Bruh ok

**Comment by sourTaste000** [comment]
Just out of curiosity, why did u tag this as good first issue?

**Comment by sourTaste000** [comment]
😂

**Comment by dominikaaaa** [comment]
it's a good issue

**Comment by sourTaste000** [comment]
cringe issue please close

**Comment by sourTaste000** [comment]
@humboldt123

**Comment by dominikaaaa** [comment]
I'll make you collaborator if you want, once I remove ban commands

**Comment by humboldt123** [comment]
Good first issue
