### ISSUE TITLE
delete warning/rule reminder after certain time

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/bot#172]
delete the rule reminder embed thing after 10 seconds or something so it doesnt get spammy when theres a cringe guy in chat

**Comment by dominikaaaa** [comment]
I'd rather just automatically mute anybody who abuses the bot commands

**Comment by humboldt123** [comment]
I would disagree. Incase of a raid, where they spam a slur, this would be really useful.

**Comment by humboldt123** [comment]
I could probably work on this later.

**Comment by dominikaaaa** [comment]
We already have different measures for raids.
