### ISSUE TITLE
AutoPaste ez

### ISSUE THREAD

**Issue by GoodPro712** [kami-blue/bot#176]
### what the thing im saying actually is
uhh, so when someone sends a log file or a big code thingy automatically converts the message to a pastebin thing and deletes the message. for lazy people basically or people who are on mobile or something.
its done in this C# bot, dunno if this helps or not
https://github.com/tModLoader/tModLoader-Discord-Bot/blob/rework/Services/HastebinService.cs
I've contributed to it :sunglasses:
ok thanks

also lol
![image](https://user-images.githubusercontent.com/45357714/91847248-bd68bd00-ec9d-11ea-99a0-1a82b13cddd5.png)

**Comment by dominikaaaa** [comment]
I can see this being more annoying then helpful

**Comment by Steviegt6** [comment]
If it were to actually be implemented, it'd most certainly be more helpful than annoying (what would make it annoying at all?).

To better describe what @GoodPro712 was getting it, when a user sends a `.log` file, the bot will automatically send a message containing a link to hastebin that has the file already pasted there (this does not delete the original file sent by the user). This is mainly helpful for people who don't want to download `.log` files when helping people.

**Comment by humboldt123** [comment]
I agree. The bot posting logs will speed up the rather annoying process of clicking on the log file, downloading it, then opening it.  Not to mention people who want to help others on mobile who have an even more annoying time viewing logs.

**Comment by humboldt123** [comment]
In my opinion, it would be easier to use [termbin](https://termbin.com/). The bot already uses this for its own internal logs and its easy to upload with it.

**Comment by dominikaaaa** [comment]
If you mean uploading actual files to paste websites, I'll do it myself
