### ISSUE TITLE
;lock and ;unlock

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/bot#25]
Quickly lock all channels during raids. 

you should be able to use this if you have manage messages permission

**Comment by humboldt123** [comment]
Would locking each channel by itself work? Something like:
```js
  message.channel.createOverwrite(message.guild.roles.everyone, {
      SEND_MESSAGES: false
  }).then(updated => console.log(updated.permissionOverwrites.get(message.author.id)));
  message.channel.send("Locked this channel!")
```

**Comment by dominikaaaa** [comment]
Yep, disable message send for @ everyone

**Comment by dominikaaaa** [comment]
You can do it to the category because the channel permissions are synced

**Comment by humboldt123** [comment]
Not quite sure how to get categories and it may be buggy? Would this work as temp solution?

**Comment by humboldt123** [comment]
Nvm got it

**Comment by humboldt123** [comment]
```js
  message.channel.parent.createOverwrite(message.guild.roles.everyone, {
      SEND_MESSAGES: false
  }).then(updated => console.log(updated.permissionOverwrites.get(message.author.id)));
  message.channel.send("Locked this channel!")
```
Something like this should work but I have not tested it.

**Comment by dominikaaaa** [comment]
lgtm

**Comment by humboldt123** [comment]
Remind me again what is the lowest role with the `MANAGE_MESSAGES` permission?

**Comment by dominikaaaa** [comment]
oh the bot would need a channel override permission to explicitly allow talking for the bot to send the confirmation

**Comment by dominikaaaa** [comment]
fixed permissions for that
