### ISSUE TITLE
;regex evaluation

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/bot#27]
Usage: `;regex ".{0,5}" "owo"`, return true if the second set of "" match the regex in the first set of ""

**Comment by humboldt123** [comment]
How is this useful?

**Comment by dominikaaaa** [comment]
Useful for quickly testing the effectiveness of a regex without having to update the bot. It's low priority anyways

**Comment by humboldt123** [comment]
Sound cool. I'll work on it.

**Comment by humboldt123** [comment]
Done!
