### ISSUE TITLE
Cheats message should blacklist chunk, chest, thank

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/bot#31]

**Comment by humboldt123** [comment]
There are legitimate reasons to use the work "Chunk" or "Chest". Why blacklist it?

**Comment by dominikaaaa** [comment]
So it doesn't trigger the cheats message

**Comment by humboldt123** [comment]
Oh I misunderstood. I thought the words "Chunk" or "Chest" should explicitly trigger the message. Could you work on the regex for that?

**Comment by dominikaaaa** [comment]
Uhhh sec

**Comment by dominikaaaa** [comment]
```
(thank|chunk|chest)
```

**Comment by dominikaaaa** [comment]
I added hink so `think` doesn't get flagged either

**Comment by humboldt123** [comment]
I have not learned Regex so how do I put that in here:  
```js
var hacksRegex = new RegExp("(ch.{0,2}t|h.{0,2}k.{0,1})");
```

**Comment by dominikaaaa** [comment]
ohhhh fuck you're right lemme do that

**Comment by dominikaaaa** [comment]
![image](https://user-images.githubusercontent.com/17222512/87878539-dac61e00-c9b2-11ea-97ca-4d026361d450.png)
```
(ch(?!es).{0,2}t|h(?!in|un|an).{0,2}k)
```

**Comment by dominikaaaa** [comment]
here's the fixed regex

**Comment by humboldt123** [comment]
Make a pull where you change line 129 of `index.js` to add that. I don't know regex lol.
```js
 var hacksRegex = new RegExp("(ch.{0,2}t|h.{0,2}k.{0,1})");
```

**Comment by humboldt123** [comment]
oh you already did lol
