### ISSUE TITLE
;updatespings

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/bot#32]
Gives / removes the updates role

**Comment by humboldt123** [comment]
We could use an alias and set it as all three
![image](https://user-images.githubusercontent.com/38266782/87876837-93d32b00-c9a8-11ea-8090-4068265d7b3d.png)

**Comment by dominikaaaa** [comment]
Yea I was pretty indecisive. ;updates is too close to ;update and ;pings doesn't make sense

**Comment by humboldt123** [comment]
#33 Done.
