### ISSUE TITLE
Cringe Command (📸)

### ISSUE THREAD

**Issue by humboldt123** [kami-blue/bot#41]
You can do `;cringe [Integer]` and it will send an embed with `📸` and an image of a "screenshot" of the chat upto that amount of messages.

**Comment by dominikaaaa** [comment]
we would need a db to store cringe for this. also it should randomly choose cringe by default

**Comment by humboldt123** [comment]
No we wouldn't. It could use `node-canvas` and just fetch the messages and avatars then send them in an embed.

**Comment by dominikaaaa** [comment]
Oh. I thought you meant the way impact did it, you can save cringe to a database and then randomly pull one with a command

**Comment by humboldt123** [comment]
No, no, no. It just sends it then and there as an embed.

**Comment by humboldt123** [comment]
Does Impact save it?

**Comment by dominikaaaa** [comment]
it saves links to a database
