### ISSUE TITLE
custom port for ;serverstat command

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/bot#51]
see title

**Comment by dominikaaaa** [comment]
what would this do

**Comment by dominikaaaa** [comment]
ohhh server port

**Comment by dominikaaaa** [comment]
![image](https://user-images.githubusercontent.com/17222512/88601980-c384d180-d03f-11ea-89f3-ba6a67953642.png)
Already supported

**Comment by sourTaste000** [comment]
pog
