### ISSUE TITLE
Filter f***

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/bot#73]

**Comment by humboldt123** [comment]
You want to have people in the KAMI Blue discord not be able to say the f-word? 🤨
![image](https://user-images.githubusercontent.com/38266782/88291421-34399000-ccc6-11ea-9d0c-c0692ba79cc6.png)

**Comment by dominikaaaa** [comment]
no, the other one

**Comment by humboldt123** [comment]
You put three asterisks.

**Comment by dominikaaaa** [comment]
I know, it was 4am
