### ISSUE TITLE
Fix hacks regex

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/bot#78]
it does jack shit

**Comment by schwarzercm** [comment]
I can try and work on that!

**Comment by dominikaaaa** [comment]
Go for it. Some examples of what I would like to flag is 
```
hack
sharkhack
hacked
hacks
```

I mean, if people try to avoid the warning then they know what they're doing, it doesn't need to be too amazing. Just a `(hack.{0,2})` or something is enough I'd say?

**Comment by dominikaaaa** [comment]
https://github.com/kami-blue/bot/blob/e53f916d856cc0a49489a9c08e295982084659d5/index.js#L150

**Comment by schwarzercm** [comment]
Right found it!

**Comment by schwarzercm** [comment]
Yeah  I've got the regex
`/s|h\w.{0,9}/g`

**Comment by dominikaaaa** [comment]
I forgot to say, it should apply to `cheat` and `cheats` as well

**Comment by schwarzercm** [comment]
yeah gonna say, forgot to include caps

**Comment by dominikaaaa** [comment]
Actually you can just do to .toLowerCase() like the other regexes do

**Comment by dominikaaaa** [comment]
Nope, those should also be detected as well. You don't need to bother with including uppercase in the regex if you just .toLowerCase() on the message

**Comment by schwarzercm** [comment]
right, cool!

**Comment by humboldt123** [comment]
It shouldn't detect shark and all the other funny stuff the the old one detected

**Comment by dominikaaaa** [comment]
No, that was caused by me being too excessive with my {0,4} lol

**Comment by dominikaaaa** [comment]
shark shouldn't be detected, sharkhack should

**Comment by schwarzercm** [comment]
I'm going to keep a list of this! 
Thanks for the heads up!

**Comment by schwarzercm** [comment]
#91

**Comment by schwarzercm** [comment]
#92
