### ISSUE TITLE
Run on Heroku

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/bot#8]
Instead of paying for hosting

**Comment by Zamazenta** [comment]
yeah have fun when u only get like 25 days of free hosting each month so your bot has average 5 day downtime each month

**Comment by dominikaaaa** [comment]
I have heroku paid for free

**Comment by Zamazenta** [comment]
ok so you mean you stole someones heroku account or someone bought it for you, therefore it still cost money

**Comment by dominikaaaa** [comment]
you have a point. 

but either way, I don't want to waste my google credits on this

**Comment by mattymatty97** [comment]
also if you make it a worker it will stay alive even if the free hours expire

**Comment by dominikaaaa** [comment]
i have a raspberry pi that works fine :sunglasses:
