### ISSUE TITLE
uwu counter

### ISSUE THREAD

**Issue by sourTaste000** [kami-blue/bot#98]
also gives percentage (howmanytimesuwu/totalmessages)

**Comment by dominikaaaa** [comment]
This would be better suited as a data analysis of the statistics. I was hoping to count amount of messages sent by each person each week, to track activity

**Comment by dominikaaaa** [comment]
but a command to just count uwus wouldn't be too hard

**Comment by sourTaste000** [comment]
just add an event in index.js

**Comment by dominikaaaa** [comment]
that wouldn't persist between restarts

**Comment by sourTaste000** [comment]
maybe write to an json file

**Comment by humboldt123** [comment]
Nope. That sounds like a bad idea. Use enmap or sqlite or literally anything but json

**Comment by dominikaaaa** [comment]
why do you hate json so much lmao

**Comment by humboldt123** [comment]
If you need to update the file on a semi-regular basis, JSON is almost guaranteed to cause errors.

**Comment by dominikaaaa** [comment]
I've never had an issue with json unless the json was empty

And you could always just have a file like this lmao
```
> uwu.txt
123
```

**Comment by dominikaaaa** [comment]
No need for any form of database

**Comment by humboldt123** [comment]
If you are using Javascript, its a bad idea. There are better solutions like enmap. I used to use JSON for one of my bots and like it would shut down every week.

**Comment by dominikaaaa** [comment]
js moment :manual_wheelchair:

**Comment by dominikaaaa** [comment]
Didn't mean to close

**Comment by sourTaste000** [comment]
ill use enmap
:thonkkill:

**Comment by humboldt123** [comment]
pog

**Comment by sourTaste000** [comment]
Now in #104

**Comment by sourTaste000** [comment]
398332c61910864836c402dedcc8ecb3f8024d23
